1vsAll:
  class_name: TrainingJob1vsAll
KvsAll:
  class_name: TrainingJobKvsAll
  label_smoothing: 0.0
  query_types:
    _po: true
    s_o: false
    sp_: true
ax_search:
  class_name: AxSearchJob
  num_sobol_trials: -1
  num_trials: 10
  parameter_constraints: []
  parameters: []
  sobol_seed: 0
console:
  format: {}
  quiet: false
dataset:
  +++: +++
  files:
    +++: +++
    entity_ids:
      filename: entity_ids.del
      type: map
    entity_strings:
      filename: entity_ids.del
      type: map
    relation_ids:
      filename: relation_ids.del
      type: map
    relation_strings:
      filename: relation_ids.del
      type: map
    test:
      filename: test.del
      type: triples
    train:
      filename: train.del
      type: triples
    valid:
      filename: valid.del
      type: triples
  name: wikidata5m_v3_semi_inductive
  num_entities: -1
  num_relations: -1
  pickle: true
distmult:
  class_name: DistMult
  entity_embedder:
    +++: +++
    type: lookup_embedder
  relation_embedder:
    +++: +++
    type: lookup_embedder
entity_ranking:
  chunk_size: 25000
  class_name: EntityRankingJob
  filter_splits:
  - train
  - valid
  filter_with_test: true
  hits_at_k_s:
  - 1
  - 3
  - 10
  - 50
  - 100
  - 200
  - 300
  - 400
  - 500
  - 1000
  metrics_per:
    argument_frequency: false
    head_and_tail: true
    relation_type: false
  tie_handling:
    atol: 1e-05
    rtol: 1e-04
    type: rounded_mean_rank
    warn_only: true
eval:
  batch_size: 256
  num_workers: 0
  pin_memory: false
  split: valid
  trace_level: epoch
  type: entity_ranking
grash_search:
  class_name: GraSHSearchJob
  cost_metric: triples
  eta: 4
  keep_initialization: false
  keep_pretrained: false
  min_negatives_percentage: 0.01
  num_trials: 64
  parameters: []
  search_budget: 3
  seed: -1
  valid_frac: 0.2
  valid_max: 5000
  variant: combined
grid_search:
  class_name: GridSearchJob
  parameters:
    +++: +++
  run: true
import:
- odistmult
- distmult
job:
  auto_correct: true
  device: cuda:0
  type: train
lookup_embedder:
  class_name: LookupEmbedder
  dim: 128
  dropout: 0.0
  initialize: xavier_uniform_
  initialize_args:
    +++: +++
    normal_:
      mean: 0.0
      std: 0.015600974164869342
    uniform_:
      a: -0.42509770087271137
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  normalize:
    p: -1.0
  pretrain:
    ensure_all: false
    model_filename: ''
  regularize: lp
  regularize_args:
    +++: +++
    p: 3
    weighted: true
  regularize_weight: 0.0
  round_dim_to: []
  space: euclidean
  sparse: true
manual_search:
  class_name: ManualSearchJob
  configurations: []
  run: true
model: odistmult
modules:
- kge.job
- kge.model
- kge.model.embedder
negative_sampling:
  class_name: TrainingJobNegativeSampling
  filtering:
    implementation: fast_if_available
    o: false
    p: false
    s: false
    split: ''
  frequency:
    smoothing: 1
  implementation: batch
  num_samples:
    o: 7467
    p: 0
    s: 5735
  sampling_type: uniform
  shared: true
  shared_type: default
  with_replacement: false
odistmult:
  class_name: ODistMult
  entity_embedder:
    +++: +++
    dropout: -0.3544049709300934
    regularize_weight: 1.6264961100212127e-10
    type: lookup_embedder
  mentions_only: true
  relation_embedder:
    +++: +++
    dropout: 0.49578630555558545
    regularize_weight: 8.552051698702295e-20
    type: lookup_embedder
random_seed:
  default: 42
  numba: 42
  numpy: 42
  python: 42
  torch: 42
search:
  device_pool:
  - cuda:0
  - cuda:1
  num_workers: 4
  on_error: abort
  type: grash_search
semi_inductive_entity_ranking:
  class_name: SemiInductiveEntityRankingJob
  context_selection: most_common
  num_shots: 10
train:
  abort_on_nan: true
  batch_size: 1024
  checkpoint:
    every: 0
    keep: 0
    keep_init: false
  loss: kl
  loss_arg: 1.0
  lr_scheduler: ''
  lr_scheduler_args:
    +++: +++
  lr_warmup: 0
  max_epochs: 64
  num_workers: 0
  optimizer:
    +++: +++
    default:
      args:
        +++: +++
        lr: 0.11345708649220962
      type: Adagrad
  pin_memory: false
  split: train
  subbatch_auto_tune: false
  subbatch_size: -1
  trace_level: epoch
  type: negative_sampling
  visualize_graph: false
training_loss:
  class_name: TrainingLossEvaluationJob
user:
  +++: +++
valid:
  early_stopping:
    patience: 0
    threshold:
      epochs: 0
      metric_value: 0.0
  every: 4
  last: true
  metric: mean_reciprocal_rank_filtered
  metric_expr: float("nan")
  metric_max: true
  split: valid
  trace_level: epoch
